name: Package released directory and README

on:
  release:
    types: [created]  # 当创建新的 release 时触发工作流

jobs:
  build:
    runs-on: ubuntu-latest  # 使用最新的 Ubuntu 环境运行

    steps:
      # Step 1: 检出仓库代码
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: 压缩 'released' 目录和 'README.md' 文件为 zip
      - name: Create zip of released and README
        run: zip -r vlook-release.zip released README.md README-en.md

      # Step 3: 将生成的 zip 文件上传到当前 release
      - name: Upload zip to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}  # 使用触发事件中的 release 上传 URL
          asset_path: ./vlook-release.zip                   # 指定要上传的 zip 文件路径
          asset_name: vlook-release.zip                     # 上传后文件的名称
          asset_content_type: application/zip                 # 指定上传文件的类型
